### ISSUE TITLE
About implement

### ISSUE THREAD

**Issue by bianjingbulb** [abdulKarim002/activityIndicator#1]
hey, friend.
Can you tell import which class file to implement this ?

**Comment by abdulKarim002** [comment]
just drag the "activityIndicator.swift" file from libTest in your project

**Comment by kodekarim** [comment]
Just drag the activityIndicator.swift file in your project and a uiview where you want to load the indicator thats it you are done and call the indicator like  > activityView.startLoading()  > activityView.progress = progress >activityView.startLoading()
         activityView.completeLoading(true)
