### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Jmeggesto** [abdulKarim002/activityIndicator#3]
Hi, what rights to reuse/modification/distribution do you intend for this library to have? If possible could you add a specific software license?

**Comment by kodekarim** [comment]
I have made this library for knowledge purpose , to know the workflow of ViewController and other things

**Comment by Jmeggesto** [comment]
Would you be okay licensing it under MIT so other people can use/modify your code?

**Comment by kodekarim** [comment]
Ya Sure go ahead

**Comment by Jmeggesto** [comment]
Well, it would help if YOU as the original author of the code added a license on your repo, then it would make it easier for people to use in their applications.

**Comment by kodekarim** [comment]
I will make a note of that.

**Comment by Jmeggesto** [comment]
Could you at least update the readme to let users know that they can
modify/reuse/etc the library?

**Comment by chrisjf** [comment]
Hi @abdulKarim002 Could you please add a LICENSE file to the repo? Example: https://choosealicense.com/licenses/mit/

**Comment by kodekarim** [comment]
Added Guys, Sorry for late response @Jmeggesto  @chrisjf
